import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:mobile_scanner/mobile_scanner.dart';

/// Extracts a product id from either a bare id or a scanned
/// `{baseUrl}/view/{id}` URL, so it doesn't matter whether the code was
/// generated by this app or typed in manually.
String? extractProductId(String value) {
  final trimmed = value.trim();
  if (trimmed.isEmpty) return null;

  final viewMatch = RegExp(r'/view/([^/?#]+)').firstMatch(trimmed);
  if (viewMatch != null) return viewMatch.group(1);

  if (!trimmed.contains('/') && !trimmed.contains(' ')) return trimmed;
  return null;
}

/// Live camera scanning is only available on Android/iOS/macOS/Web
/// (mobile_scanner has no Windows/Linux desktop camera support, and neither
/// does the alternative FFI-based scanner). Windows/Linux native builds —
/// and anyone who prefers not to use the camera — get a manual entry field
/// instead. The web build is the practical way to scan on a Windows/Linux
/// desktop, since the browser handles webcam access itself.
bool get _supportsCameraScanning =>
    kIsWeb ||
    defaultTargetPlatform == TargetPlatform.android ||
    defaultTargetPlatform == TargetPlatform.iOS ||
    defaultTargetPlatform == TargetPlatform.macOS;

class ScannerPage extends StatefulWidget {
  const ScannerPage({super.key});

  @override
  State<ScannerPage> createState() => _ScannerPageState();
}

class _ScannerPageState extends State<ScannerPage> {
  final _manualController = TextEditingController();
  bool _manualEntry = !_supportsCameraScanning;
  bool _navigated = false;

  @override
  void dispose() {
    _manualController.dispose();
    super.dispose();
  }

  void _goToProduct(String rawValue) {
    if (_navigated) return;
    final productId = extractProductId(rawValue);
    if (productId == null) return;
    _navigated = true;
    context.go('/view/$productId');
  }

  void _onDetect(BarcodeCapture capture) {
    for (final barcode in capture.barcodes) {
      final value = barcode.rawValue;
      if (value != null) {
        _goToProduct(value);
        return;
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Scan QR Code'),
        actions: [
          if (_supportsCameraScanning)
            IconButton(
              icon: Icon(_manualEntry ? Icons.qr_code_scanner : Icons.keyboard),
              tooltip: _manualEntry ? 'Use camera' : 'Enter manually',
              onPressed: () => setState(() => _manualEntry = !_manualEntry),
            ),
        ],
      ),
      body: _manualEntry ? _buildManualEntry(context) : _buildCameraView(),
    );
  }

  Widget _buildCameraView() {
    return MobileScanner(onDetect: _onDetect);
  }

  Widget _buildManualEntry(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 400),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              if (!_supportsCameraScanning) ...[
                const Text(
                  'Live camera scanning isn\'t available on this platform yet. '
                  'Open this app in a web browser to scan with a webcam, or '
                  'paste a product link or id below.',
                ),
                const SizedBox(height: 16),
              ],
              TextField(
                controller: _manualController,
                decoration: const InputDecoration(
                  labelText: 'Product link or id',
                  prefixIcon: Icon(Icons.link),
                ),
                onSubmitted: _goToProduct,
              ),
              const SizedBox(height: 16),
              FilledButton(
                onPressed: () => _goToProduct(_manualController.text),
                child: const Text('Go'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
